language: node_js
node_js:
  - "stable"
cache: node_modules
script:
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: react-typescript-ios-calculator.surge.sh
  project: ./build/
on: branch:master
